# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('working_address', models.CharField(default='', max_length=200)),
                ('work_mobile', models.CharField(default='', max_length=12)),
                ('work_location', models.CharField(default='', max_length=200)),
                ('work_email', models.EmailField(default='', max_length=254)),
                ('work_phone', models.CharField(default='', max_length=12)),
                ('public_info', models.CharField(default='', max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', encrypted_fields.fields.EncryptedCharField(default='', max_length=100)),
                ('dc_type', encrypted_fields.fields.EncryptedCharField(default='', max_length=50)),
                ('wage', encrypted_fields.fields.EncryptedFloatField(default=0.0)),
                ('salary_struct', encrypted_fields.fields.EncryptedCharField(default='', max_length=100)),
                ('tp_duration_begin', encrypted_fields.fields.EncryptedDateField(default='')),
                ('tp_duration_end', encrypted_fields.fields.EncryptedDateField(default='')),
                ('duration_begin', encrypted_fields.fields.EncryptedDateField(default='')),
                ('duration_end', encrypted_fields.fields.EncryptedDateField(default='')),
                ('schedule', encrypted_fields.fields.EncryptedIntegerField(default=0)),
                ('pay_schedule', encrypted_fields.fields.EncryptedIntegerField(default=0)),
                ('visa_no', encrypted_fields.fields.EncryptedCharField(default='', max_length=50)),
                ('visa_expiry', encrypted_fields.fields.EncryptedDateField(default='')),
                ('work_permit_no', encrypted_fields.fields.EncryptedCharField(default='', max_length=50)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapi.Employee')),
            ],
        ),
    ]
