# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 10:35
from __future__ import unicode_literals

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_auto_20180729_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='duration_begin',
            field=encrypted_fields.fields.EncryptedDateField(default=None),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='duration_end',
            field=encrypted_fields.fields.EncryptedDateField(default=None),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='tp_duration_begin',
            field=encrypted_fields.fields.EncryptedDateField(default=None),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='tp_duration_end',
            field=encrypted_fields.fields.EncryptedDateField(default=None),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='visa_expiry',
            field=encrypted_fields.fields.EncryptedDateField(default=None),
        ),
    ]
