# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_auto_20180729_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
