# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest', '0002_testcrypt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('working_address', models.CharField(max_length=200)),
                ('work_mobile', models.CharField(max_length=12)),
                ('work_location', models.CharField(max_length=200)),
                ('work_email', models.EmailField(max_length=254)),
                ('work_phone', models.CharField(max_length=12)),
                ('public_info', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('job_title', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('dc_type', encrypted_fields.fields.EncryptedCharField(max_length=50)),
                ('wage', encrypted_fields.fields.EncryptedFloatField()),
                ('salary_struct', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('tp_duration_begin', encrypted_fields.fields.EncryptedDateField()),
                ('tp_duration_end', encrypted_fields.fields.EncryptedDateField()),
                ('duration_begin', encrypted_fields.fields.EncryptedDateField()),
                ('duration_end', encrypted_fields.fields.EncryptedDateField()),
                ('schedule', encrypted_fields.fields.EncryptedIntegerField()),
                ('pay_schedule', encrypted_fields.fields.EncryptedIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeWorkPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('visa_no', encrypted_fields.fields.EncryptedCharField(max_length=50)),
                ('visa_expiry', encrypted_fields.fields.EncryptedDateField()),
                ('work_permit_no', encrypted_fields.fields.EncryptedCharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='work_permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest.EmployeeWorkPermit'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest.EmployeeContract'),
        ),
    ]
