# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest', '0003_auto_20180727_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCrypt',
        ),
    ]
