# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest', '0005_auto_20180727_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest.EmployeeContract', unique=True),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='work_permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest.EmployeeWorkPermit', unique=True),
        ),
    ]
