# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest', '0007_auto_20180727_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='employeecontract',
            name='work_permit',
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_rest.Employee'),
        ),
        migrations.AlterField(
            model_name='employeeworkpermit',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_rest.EmployeeContract'),
        ),
    ]
