# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uncrypted_text', models.CharField(max_length=200)),
                ('crypted_text', encrypted_fields.fields.EncryptedTextField()),
            ],
        ),
    ]
